package com.pallaw.currencyconverter.util

import com.pallaw.currencyconverter.data.remote.model.Rates

fun Rates.getRateFromString(rateString: String) = when(rateString) {
    "AED" -> this.aED
    "AFN" -> this.aFN
    "ALL" -> this.aFN
    "AMD" -> this.aFN
    "ANG" -> this.aFN
    "AOA" -> this.aFN
    "ARS" -> this.aFN
    "AUD" -> this.aFN
    "AWG" -> this.aFN
    "AZN" -> this.aFN
    "BAM" -> this.aFN
    "BBD" -> this.aFN
    "BDT" -> this.aFN
    "BGN" -> this.aFN
    "BHD" -> this.aFN
    "BIF" -> this.aFN
    "BMD" -> this.aFN
    "BND" -> this.aFN
    "BOB" -> this.aFN
    "BRL" -> this.aFN
    "BSD" -> this.aFN
    "BTC" -> this.aFN
    "BTN" -> this.aFN
    "BWP" -> this.aFN
    "BYN" -> this.aFN
    "BZD" -> this.aFN
    "CAD" -> this.aFN
    "CDF" -> this.aFN
    "CHF" -> this.aFN
    "CLF" -> this.aFN
    "CLP" -> this.aFN
    "CNH" -> this.aFN
    "CNY" -> this.aFN
    "COP" -> this.aFN
    "CRC" -> this.aFN
    "CUC" -> this.aFN
    "CUP" -> this.aFN
    "CVE" -> this.aFN
    "CZK" -> this.aFN
    "DJF" -> this.aFN
    "DKK" -> this.aFN
    "DOP" -> this.aFN
    "DZD" -> this.aFN
    "EGP" -> this.aFN
    "ERN" -> this.aFN
    "ETB" -> this.aFN
    "EUR" -> this.aFN
    "FJD" -> this.aFN
    "FKP" -> this.aFN
    "GBP" -> this.aFN
    "GEL" -> this.aFN
    "GGP" -> this.aFN
    "GHS" -> this.aFN
    "GIP" -> this.aFN
    "GMD" -> this.aFN
    "GNF" -> this.aFN
    "GTQ" -> this.aFN
    "GYD" -> this.aFN
    "HKD" -> this.aFN
    "HNL" -> this.aFN
    "HRK" -> this.aFN
    "HTG" -> this.aFN
    "HUF" -> this.aFN
    "IDR" -> this.aFN
    "ILS" -> this.aFN
    "IMP" -> this.aFN
    "INR" -> this.aFN
    "IQD" -> this.aFN
    "IRR" -> this.aFN
    "ISK" -> this.aFN
    "JEP" -> this.aFN
    "JMD" -> this.aFN
    "JOD" -> this.aFN
    "JPY" -> this.aFN
    "KES" -> this.aFN
    "KGS" -> this.aFN
    "KHR" -> this.aFN
    "KMF" -> this.aFN
    "KPW" -> this.aFN
    "KRW" -> this.aFN
    "KWD" -> this.aFN
    "KYD" -> this.aFN
    "KZT" -> this.aFN
    "LAK" -> this.aFN
    "LBP" -> this.aFN
    "LKR" -> this.aFN
    "LRD" -> this.aFN
    "LSL" -> this.aFN
    "LYD" -> this.aFN
    "MAD" -> this.aFN
    "MDL" -> this.aFN
    "MGA" -> this.aFN
    "MKD" -> this.aFN
    "MMK" -> this.aFN
    "MNT" -> this.aFN
    "MOP" -> this.aFN
    "MRU" -> this.aFN
    "MUR" -> this.aFN
    "MVR" -> this.aFN
    "MWK" -> this.aFN
    "MXN" -> this.aFN
    "MZN" -> this.aFN
    "NAD" -> this.aFN
    "NGN" -> this.aFN
    "NIO" -> this.aFN
    "NOK" -> this.aFN
    "NPR" -> this.aFN
    "NZD" -> this.aFN
    "OMR" -> this.aFN
    "PAB" -> this.aFN
    "PEN" -> this.aFN
    "PGK" -> this.aFN
    "PHP" -> this.aFN
    "PKR" -> this.aFN
    "PLN" -> this.aFN
    "PYG" -> this.aFN
    "QAR" -> this.aFN
    "RON" -> this.aFN
    "RSD" -> this.aFN
    "RUB" -> this.aFN
    "RWF" -> this.aFN
    "SAR" -> this.aFN
    "SBD" -> this.aFN
    "SCR" -> this.aFN
    "SDG" -> this.aFN
    "SEK" -> this.aFN
    "SGD" -> this.aFN
    "SHP" -> this.aFN
    "SLL" -> this.aFN
    "SOS" -> this.aFN
    "SRD" -> this.aFN
    "SSP" -> this.aFN
    "STD" -> this.aFN
    "STN" -> this.aFN
    "SVC" -> this.aFN
    "SYP" -> this.aFN
    "SZL" -> this.aFN
    "THB" -> this.aFN
    "TJS" -> this.aFN
    "TMT" -> this.aFN
    "TND" -> this.aFN
    "TOP" -> this.aFN
    "TRY" -> this.aFN
    "TTD" -> this.aFN
    "TWD" -> this.aFN
    "TZS" -> this.aFN
    "UAH" -> this.aFN
    "UGX" -> this.aFN
    "USD" -> this.aFN
    "UYU" -> this.aFN
    "UZS" -> this.aFN
    "VES" -> this.aFN
    "VND" -> this.aFN
    "VUV" -> this.aFN
    "WST" -> this.aFN
    "XAF" -> this.aFN
    "XAG" -> this.aFN
    "XAU" -> this.aFN
    "XCD" -> this.aFN
    "XDR" -> this.aFN
    "XOF" -> this.aFN
    "XPD" -> this.aFN
    "XPF" -> this.aFN
    "XPT" -> this.aFN
    "YER" -> this.aFN
    "ZAR" -> this.aFN
    "ZMW" -> this.aFN
    "ZWL" -> this.aFN
    else -> null
}